1. Fix error params done 2. Introduce crypto sha256

diff --git a/reference-monitor/Makefile b/reference-monitor/Makefile
--- a/reference-monitor/Makefile
+++ b/reference-monitor/Makefile
@@ -1,5 +1,5 @@
-obj-m += reference_monitor.o
-the_rm-objs := reference_monitor.o utils.o
+obj-m += the_reference_monitor.o
+the_reference_monitor-objs := reference_monitor.o utils.o
 
 all:
 	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
@@ -9,4 +9,14 @@ clean:
 
 mount: 
 	@read -p "Select a password: " password; \
-	sudo insmod reference_monitor.ko the_syscall_table=$$(cat /sys/module/the_usctm/parameters/sys_call_table_address) password="$$password"
+	sudo insmod the_reference_monitor.ko the_syscall_table=$$(sudo cat /sys/module/the_usctm/parameters/sys_call_table_address) password="$$password"
+
+#@stty -echo
+#@read -p "Select a password: " password; echo
+#	@stty echo
+#	@if [ ! -f /sys/module/the_usctm/parameters/sys_call_table_address ]; then \
+		echo "Error: sys_call_table_address not found. Is the_usctm module loaded?"; \
+		exit 1; \
+	fi
+#	@syscall_table=$$(sudo cat /sys/module/the_usctm/parameters/sys_call_table_address) && \
+#	sudo insmod reference_monitor.ko the_syscall_table=$$syscall_table password="$$password"
